apiVersion: v2
name: typesense-operator
description: >-
  Typesense Kubernetes Operator (TyKO) simplifies deploying, scaling and
  managing highly-available, self-healing Typesense clusters in Kubernetes
icon: https://akyriako.github.io/typesense-operator-docs/img/tyko-logo.png
type: application
version: 0.6.0
appVersion: 0.6.0
maintainers:
  - name: Kyriakos Akriotis
    url: https://github.com/akyriako
